### PR TITLE
Add comment

### PR DESCRIPTION
**Pull request by willtebbutt**
Addresses #67

### CODE REVIEW

**Comment by theogf** [comment]
BTW any reason `SVGP` is not an `AbstractGP` ?

**Comment by st--** [comment]
> BTW any reason `SVGP` is not an `AbstractGP` ?

Mhmm, I see it as more like `LaplaceApproximation()` than `GP()`. A way of specifying an approximation, not a GP in itself (the GP itself you get by calling `posterior(...)` on it)

**Comment by willtebbutt** [comment]
Agreed @st-- . This might be a good candidate for re-naming, because SVGP is literally "sparse variational Gaussian Process", which makes it sound an awful lot like it ought to be a GP. Perhaps we should go with something like `SparseVariationalApproximation`

**Comment by rossviljoen** [comment]
I'm in favour of renaming to `SparseVariationalApproximation`

**Comment by willtebbutt** [comment]
Excellent. I've opened in a new issue so that we don't forget. @theogf is there anything else, or are you happy for this to approve?

**Review by theogf — APPROVED** [review]

**Pull request merged**
